### ISSUE TITLE
isDragDisabled / allowing only some items to be draggable

### ISSUE THREAD

**Issue by drcmda** [tajo/react-movable#6] opened 2019-02-14 09:49 UTC
Thanks for making this awesome lib! We are replacing react-beuatiful-dnd as this is smaller and easier to handle, and it works fantastic so far but there's one thing i can't find. In our list only one element can be dragged, the others shouldn't be. In b-dnd there's a isDragDisabled flag, is there something like this here? And if not, could it be added?

**Comment by tajo** [comment] 2019-02-14 20:26
There is no official API for this now, although I think it would be a good addition. I can imagine some `disabledItems` List prop. Maybe:

```jsx
<List disabledItems={[0, 2, 3]} />
```

Would make items with index 0, 2 and 3 not draggable - they would receive additional flag `isDisabled`.

Anyway, there is a hacky workaround, if you want to disable specific item now. You can add

```jsx
<span data-movable-handle />
```

anywhere into the rendered item. It will create an invisible drag handle and that disables the rest of the item:

https://codesandbox.io/s/n02z41jw54

**Comment by VuongN** [comment] 2019-02-14 20:30
I would make the "disabled" or "draggable" attribute be self-contained inside the item object itself rather than going for a "index-based" disabledItems prop. Just a thought.

**Comment by VuongN** [comment] 2019-02-14 20:44
https://github.com/tajo/react-movable/blob/master/src/List.tsx#L139
Took a quick look at this, and I'd imagine getting the actual item object using known `index` key and simply convert `if (index === -1) return;` to `if (item.index === -1 || item.disabled) return;`

**Comment by tajo** [comment] 2019-02-14 20:58
The problem is there is no such thing as `item` object right now. We could extend the `values` prop so instead of: 

```jsx
<List value={['Item 1', 'Item 2']} />
```

you would do

```jsx
<List value={[{ value: 'Item 1', disabled: true}, { value: 'Item 2' }]} />
```

That's why I proposed the additional "index-based" prop.

**Comment by VuongN** [comment] 2019-02-14 21:02
Yeah, I was playing with the code, and realized that you got value to be "string" - I think we should do a thing were we have an interface for an item object. You can pass in string,  but internally, we should control the shape of item to have a basic level of internal API.

**Comment by VuongN** [comment] 2019-02-14 21:22
Just a prototype: https://github.com/VuongN/react-movable/tree/disabled-item
If this is interesting, I'd define a good interface for Item and then of course, test :)

(By the way @tajo, would consider moving to https://datasift.github.io/gitflow/IntroducingGitFlow.html to make collaboration a bit more organized? I see only 'master' but not 'develop' branch, so I'm assuming repos is not following git flow - if you're already doing something like that, then we're good)

**Comment by tajo** [comment] 2019-02-14 22:01
> Just a prototype: https://github.com/VuongN/react-movable/tree/disabled-item
If this is interesting, I'd define a good interface for Item and then of course, test :)

Yea, that looks good to me (except my [comment](https://github.com/VuongN/react-movable/commit/ffb33c04a63d58873dd97db2a418e9a941c9507a#r32325590), also it doesn't cover keyboard controls). What @drcmda thinks? I want to make sure it solves their use-case as well.

> By the way @tajo, would consider moving to https://datasift.github.io/gitflow/IntroducingGitFlow.html to make collaboration a bit more organized?

Meh, I don't see a need for this. It's way too pre-mature for the project of this size, deving off master should work just fine for now.

**Comment by tajo** [comment] 2019-02-14 22:07
Also, I am interested to see how the "rollbar" question relates to this. I feel those two are a part of the same use-case, so we might consider an API for both.

**Comment by tajo** [comment] 2019-07-01 21:24
The `beforeDrag` API has been added as `v2.1.1`

**Closed by tajo** 2019-07-01 21:24 UTC
Labels: enhancement

**Comment by drcmda** [comment] 2019-07-02 07:08
@tajo how would i use it to tell one element that it can be dragged while the others wouldn't respond?

**Comment by tajo** [comment] 2019-07-02 17:47
> @tajo how would i use it to tell one element that it can be dragged while the others wouldn't respond?

You would set `disabled: true` to all other items. [Example](https://github.com/tajo/react-movable/blob/master/examples/Disabled.tsx#L12-L13).

**Comment by drcmda** [comment] 2019-07-03 10:50
perfect, we're all set now, everything we needed is in, thanks so much!

**Comment by chinanderm** [comment] 2021-01-28 02:35
In case the example isn't too clear on how to disable an item, the property `disabled` must be added to an item in the array of values. Doesn't help keeping your object structure in-tact but I guess it works fine. I wish it was an explicit property to set on the `renderItem` element so I didn't have to modify my value object (I'm using Typescript).

**Comment by vtarelkin** [comment] 2022-10-04 20:10
@tajo hi! how could I forbid certain item to be moved at certain position? In onChange handle I only have indexes, but not the value of the dragging item itself
